theme: jekyll-theme-slate
github:
  is_project_page: false
title: Missouri’s 44-Network Information Center
description: AMPRnet Coordinator's Wiki & FAQs
show_downloads: false
google_analytics: G-JG5KG0842D
